services:
  server:
    image: cr.yandex/crpepnp6t24n31l71vv9/soa-2
    environment:
      SERVER: 'true'
    ports:
      - '8443:8443'
  client1:
    image: cr.yandex/crpepnp6t24n31l71vv9/soa-2-client
    command:
      - --address
      - 'server:8443'
  client2: &client
    image: cr.yandex/crpepnp6t24n31l71vv9/soa-2-client
    command:
      - --address
      - 'server:8443'
      - --join-existing
  client3:
    <<: *client
  client4:
    <<: *client

