// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: citizen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CitizenVoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// id of the sender
	ParticipantId string `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// id of the participant who should be executed
	SuspectedId string `protobuf:"bytes,3,opt,name=suspected_id,json=suspectedId,proto3" json:"suspected_id,omitempty"`
}

func (x *CitizenVoteRequest) Reset() {
	*x = CitizenVoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_citizen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitizenVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenVoteRequest) ProtoMessage() {}

func (x *CitizenVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_citizen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenVoteRequest.ProtoReflect.Descriptor instead.
func (*CitizenVoteRequest) Descriptor() ([]byte, []int) {
	return file_citizen_proto_rawDescGZIP(), []int{0}
}

func (x *CitizenVoteRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CitizenVoteRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CitizenVoteRequest) GetSuspectedId() string {
	if x != nil {
		return x.SuspectedId
	}
	return ""
}

type CitizenVoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CitizenVoteResponse) Reset() {
	*x = CitizenVoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_citizen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitizenVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenVoteResponse) ProtoMessage() {}

func (x *CitizenVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_citizen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenVoteResponse.ProtoReflect.Descriptor instead.
func (*CitizenVoteResponse) Descriptor() ([]byte, []int) {
	return file_citizen_proto_rawDescGZIP(), []int{1}
}

var File_citizen_proto protoreflect.FileDescriptor

var file_citizen_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x22, 0x77, 0x0a,
	0x12, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65,
	0x6e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7d, 0x0a,
	0x0e, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6b, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x2e, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x56, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x2e, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e,
	0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x61, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_citizen_proto_rawDescOnce sync.Once
	file_citizen_proto_rawDescData = file_citizen_proto_rawDesc
)

func file_citizen_proto_rawDescGZIP() []byte {
	file_citizen_proto_rawDescOnce.Do(func() {
		file_citizen_proto_rawDescData = protoimpl.X.CompressGZIP(file_citizen_proto_rawDescData)
	})
	return file_citizen_proto_rawDescData
}

var file_citizen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_citizen_proto_goTypes = []interface{}{
	(*CitizenVoteRequest)(nil),  // 0: com.example.demo.api.citizen.CitizenVoteRequest
	(*CitizenVoteResponse)(nil), // 1: com.example.demo.api.citizen.CitizenVoteResponse
}
var file_citizen_proto_depIdxs = []int32{
	0, // 0: com.example.demo.api.citizen.CitizenService.Vote:input_type -> com.example.demo.api.citizen.CitizenVoteRequest
	1, // 1: com.example.demo.api.citizen.CitizenService.Vote:output_type -> com.example.demo.api.citizen.CitizenVoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_citizen_proto_init() }
func file_citizen_proto_init() {
	if File_citizen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_citizen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitizenVoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_citizen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitizenVoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_citizen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_citizen_proto_goTypes,
		DependencyIndexes: file_citizen_proto_depIdxs,
		MessageInfos:      file_citizen_proto_msgTypes,
	}.Build()
	File_citizen_proto = out.File
	file_citizen_proto_rawDesc = nil
	file_citizen_proto_goTypes = nil
	file_citizen_proto_depIdxs = nil
}
