// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: criminal.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CriminalServiceClient is the client API for CriminalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CriminalServiceClient interface {
	Vote(ctx context.Context, in *CriminalVoteRequest, opts ...grpc.CallOption) (*CriminalVoteResponse, error)
}

type criminalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCriminalServiceClient(cc grpc.ClientConnInterface) CriminalServiceClient {
	return &criminalServiceClient{cc}
}

func (c *criminalServiceClient) Vote(ctx context.Context, in *CriminalVoteRequest, opts ...grpc.CallOption) (*CriminalVoteResponse, error) {
	out := new(CriminalVoteResponse)
	err := c.cc.Invoke(ctx, "/com.example.demo.api.criminal.CriminalService/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CriminalServiceServer is the server API for CriminalService service.
// All implementations must embed UnimplementedCriminalServiceServer
// for forward compatibility
type CriminalServiceServer interface {
	Vote(context.Context, *CriminalVoteRequest) (*CriminalVoteResponse, error)
	mustEmbedUnimplementedCriminalServiceServer()
}

// UnimplementedCriminalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCriminalServiceServer struct {
}

func (UnimplementedCriminalServiceServer) Vote(context.Context, *CriminalVoteRequest) (*CriminalVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedCriminalServiceServer) mustEmbedUnimplementedCriminalServiceServer() {}

// UnsafeCriminalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CriminalServiceServer will
// result in compilation errors.
type UnsafeCriminalServiceServer interface {
	mustEmbedUnimplementedCriminalServiceServer()
}

func RegisterCriminalServiceServer(s grpc.ServiceRegistrar, srv CriminalServiceServer) {
	s.RegisterService(&CriminalService_ServiceDesc, srv)
}

func _CriminalService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriminalVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriminalServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.demo.api.criminal.CriminalService/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriminalServiceServer).Vote(ctx, req.(*CriminalVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CriminalService_ServiceDesc is the grpc.ServiceDesc for CriminalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CriminalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.example.demo.api.criminal.CriminalService",
	HandlerType: (*CriminalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vote",
			Handler:    _CriminalService_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "criminal.proto",
}
