/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.formats.avro;
@org.apache.avro.specific.AvroGenerated
public enum AvroCustomerStatus implements org.apache.avro.generic.GenericEnumSymbol<AvroCustomerStatus> {
  ALIVE, DEAD, DEAD_INSIDE, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroCustomerStatus\",\"namespace\":\"com.example.demo.formats.avro\",\"symbols\":[\"ALIVE\",\"DEAD\",\"DEAD_INSIDE\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
